# Site settings
name: Jesus Ortiz
email: blog.jesusortiz@gmail.com
url: url
description: " "
author: "Jesus Ortiz"
title: "Jesus' Quarantine Blog"
permalink: pretty
baseurl:

# social
github:
  username: jorti1

twitter:
  username:
