# Site settings
name: Jesus Ortiz
email: blog.jesusortiz@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "Jesus' Quarantine"
permalink: pretty
baseurl: /Jesus%Quarantine

# social
github:
  username: jorti1
twitter:
  username: 