# Site settings
name: Jesus Ortiz
email: blog.jesusortiz@gmail.com
url: url
description: "A blog made during quarantine"
author: "Jesus Ortiz"
title: "Jesus' Quarantine"
permalink: pretty
baseurl: /Jesus-Quarantine

# social
github:
  username: jorti1

twitter:
  username:
